development:
  adapter: postgresql
  encoding: utf8
  database: maphub_development
  username: maphub
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: maphub_test
  username: maphub
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: maphub_production     
