development:
  adapter: postgresql
  encoding: unicode
  database: maphub_development
  pool: 5
  username: haslhofer
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: maphub_test
  pool: 5
  username: haslhofer
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: maphub_production
  pool: 5
  username: haslhofer
  password:
     