production:
  solr:
    hostname: samos.mminf.univie.ac.at
    port: 8983
    log_level: WARNING

development:
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING